DROP VIEW SAPABAP1.CV_EQUIPMENT_STATUSES CASCADE;
CREATE VIEW SAPABAP1.CV_EQUIPMENT_STATUSES AS
WITH
  projection_5 AS (
    SELECT
        SAPABAP1."/BIC/AZTJ02T2".ISTAT AS ISTAT,
        SAPABAP1."/BIC/AZTJ02T2".SPRAS AS SPRAS,
        SAPABAP1."/BIC/AZTJ02T2".TXT04 AS TXT04_TJ02T,
        SAPABAP1."/BIC/AZTJ02T2".TXT30 AS TXT30_TJ02T
    FROM SAPABAP1."/BIC/AZTJ02T2"
  ),
  projection_3 AS (
    SELECT
        SAPABAP1."/BIC/AZJCDS2".OBJNR AS OBJNR_JCDS,
        SAPABAP1."/BIC/AZJCDS2".STAT AS STAT_JCDS,
        SAPABAP1."/BIC/AZJCDS2".CHGNR AS CHGNR_JCDS,
        SAPABAP1."/BIC/AZJCDS2".USNAM AS USNAM_JCDS,
        SAPABAP1."/BIC/AZJCDS2".UDATE AS UDATE_JCDS,
        SAPABAP1."/BIC/AZJCDS2".UTIME AS UTIME_JCDS,
        SAPABAP1."/BIC/AZJCDS2".TCODE AS TCODE_JCDS,
        SAPABAP1."/BIC/AZJCDS2".CDTCODE AS CDTCODE_JCDS,
        SAPABAP1."/BIC/AZJCDS2".INACT AS INACT_JCDS,
        SAPABAP1."/BIC/AZJCDS2".CHIND AS CHIND_JCDS
    FROM SAPABAP1."/BIC/AZJCDS2"
  ),
  projection_1 AS (
    SELECT
        SAPABAP1."/BIC/AZEQUI2".EQUNR AS EQUNR_EQUI,
        SAPABAP1."/BIC/AZEQUI2".OBJNR AS OBJNR_EQUI,
        SAPABAP1."/BIC/AZEQUI2".ANSWT AS ANSWT_EQUI,
        SAPABAP1."/BIC/AZEQUI2".WAERS AS WAERS_EQUI
    FROM SAPABAP1."/BIC/AZEQUI2"
  ),
  projection_2 AS (
    SELECT
        SAPABAP1."/BIC/AZJEST2".OBJNR AS OBJNR_JEST,
        SAPABAP1."/BIC/AZJEST2".STAT AS STAT_JEST,
        SAPABAP1."/BIC/AZJEST2".INACT AS INACT_JEST,
        SAPABAP1."/BIC/AZJEST2".CHGNR AS CHGNR_JEST
    FROM SAPABAP1."/BIC/AZJEST2"
  ),
  projection_4 AS (
    SELECT
        SAPABAP1."/BIC/AZTJ30T2".STSMA AS STSMA,
        SAPABAP1."/BIC/AZTJ30T2".SPRAS AS SPRAS,
        SAPABAP1."/BIC/AZTJ30T2".ESTAT AS ESTAT,
        SAPABAP1."/BIC/AZTJ30T2".TXT04 AS TXT04_TJ30T,
        SAPABAP1."/BIC/AZTJ30T2".TXT30 AS TXT30_TJ30T,
        SAPABAP1."/BIC/AZTJ30T2".LTEXT AS LTEXT_TJ30T
    FROM SAPABAP1."/BIC/AZTJ30T2"
  ),
  join_1 AS (
    SELECT
        projection_1.EQUNR_EQUI AS EQUNR_EQUI,
        projection_1.OBJNR_EQUI AS OBJNR_EQUI,
        projection_1.ANSWT_EQUI AS ANSWT_EQUI,
        projection_1.WAERS_EQUI AS WAERS_EQUI,
        projection_2.STAT_JEST AS STAT_JEST,
        projection_2.INACT_JEST AS INACT_JEST,
        projection_2.CHGNR_JEST AS CHGNR_JEST
    FROM projection_1
    INNER JOIN projection_2 ON projection_1.OBJNR_EQUI = projection_2.OBJNR_JEST
  ),
  join_2 AS (
    SELECT
        join_1.EQUNR_EQUI AS EQUNR_EQUI,
        join_1.OBJNR_EQUI AS OBJNR_EQUI,
        join_1.STAT_JEST AS STAT_JEST,
        join_1.INACT_JEST AS INACT_JEST,
        join_1.CHGNR_JEST AS CHGNR_JEST,
        join_1.ANSWT_EQUI AS ANSWT_EQUI,
        join_1.WAERS_EQUI AS WAERS_EQUI,
        projection_3.OBJNR_JCDS AS OBJNR_JCDS,
        projection_3.STAT_JCDS AS STAT_JCDS,
        projection_3.CHGNR_JCDS AS CHGNR_JCDS,
        projection_3.USNAM_JCDS AS USNAM_JCDS,
        projection_3.UDATE_JCDS AS UDATE_JCDS,
        projection_3.UTIME_JCDS AS UTIME_JCDS,
        projection_3.TCODE_JCDS AS TCODE_JCDS,
        projection_3.CDTCODE_JCDS AS CDTCODE_JCDS,
        projection_3.INACT_JCDS AS INACT_JCDS,
        projection_3.CHIND_JCDS AS CHIND_JCDS,
        DAYS_BETWEEN(TO_DATE("UDATE_JCDS"), CURRENT_TIMESTAMP) AS DURATION
    FROM join_1
    INNER JOIN projection_3 ON join_1.OBJNR_EQUI = projection_3.OBJNR_JCDS AND join_1.STAT_JEST = projection_3.STAT_JCDS AND join_1.CHGNR_JEST = projection_3.CHGNR_JCDS
  ),
  join_3 AS (
    SELECT
        join_2.EQUNR_EQUI AS EQUNR_EQUI,
        join_2.OBJNR_EQUI AS OBJNR_EQUI,
        join_2.STAT_JEST AS STAT_JEST,
        join_2.INACT_JEST AS INACT_JEST,
        join_2.CHGNR_JEST AS CHGNR_JEST,
        join_2.OBJNR_JCDS AS OBJNR_JCDS,
        join_2.STAT_JCDS AS STAT_JCDS,
        join_2.CHGNR_JCDS AS CHGNR_JCDS,
        join_2.USNAM_JCDS AS USNAM_JCDS,
        join_2.UDATE_JCDS AS UDATE_JCDS,
        join_2.UTIME_JCDS AS UTIME_JCDS,
        join_2.TCODE_JCDS AS TCODE_JCDS,
        join_2.CDTCODE_JCDS AS CDTCODE_JCDS,
        join_2.INACT_JCDS AS INACT_JCDS,
        join_2.CHIND_JCDS AS CHIND_JCDS,
        join_2.ANSWT_EQUI AS ANSWT_EQUI,
        join_2.WAERS_EQUI AS WAERS_EQUI,
        join_2.DURATION AS DURATION,
        projection_4.TXT04_TJ30T AS TXT04_TJ30T,
        projection_4.TXT30_TJ30T AS TXT30_TJ30T,
        projection_4.LTEXT_TJ30T AS LTEXT_TJ30T
    FROM join_2
    LEFT OUTER JOIN projection_4 ON join_2.STAT_JEST = projection_4.ESTAT
  ),
  join_4 AS (
    SELECT
        join_3.EQUNR_EQUI AS EQUNR_EQUI,
        join_3.OBJNR_EQUI AS OBJNR_EQUI,
        join_3.STAT_JEST AS STAT_JEST,
        join_3.INACT_JEST AS INACT_JEST,
        join_3.CHGNR_JEST AS CHGNR_JEST,
        join_3.OBJNR_JCDS AS OBJNR_JCDS,
        join_3.STAT_JCDS AS STAT_JCDS,
        join_3.CHGNR_JCDS AS CHGNR_JCDS,
        join_3.USNAM_JCDS AS USNAM_JCDS,
        join_3.UDATE_JCDS AS UDATE_JCDS,
        join_3.UTIME_JCDS AS UTIME_JCDS,
        join_3.TCODE_JCDS AS TCODE_JCDS,
        join_3.CDTCODE_JCDS AS CDTCODE_JCDS,
        join_3.INACT_JCDS AS INACT_JCDS,
        join_3.CHIND_JCDS AS CHIND_JCDS,
        join_3.ANSWT_EQUI AS ANSWT_EQUI,
        join_3.WAERS_EQUI AS WAERS_EQUI,
        join_3.DURATION AS DURATION,
        join_3.TXT04_TJ30T AS TXT04_TJ30T,
        join_3.TXT30_TJ30T AS TXT30_TJ30T,
        join_3.LTEXT_TJ30T AS LTEXT_TJ30T,
        projection_5.TXT04_TJ02T AS TXT04_TJ02T,
        projection_5.TXT30_TJ02T AS TXT30_TJ02T
    FROM join_3
    LEFT OUTER JOIN projection_5 ON join_3.STAT_JEST = projection_5.ISTAT
  ),
  projection AS (
    SELECT
        join_4.EQUNR_EQUI AS EQUNR_EQUI,
        join_4.OBJNR_EQUI AS OBJNR_EQUI,
        join_4.STAT_JEST AS STAT_JEST,
        join_4.INACT_JEST AS INACT_JEST,
        join_4.CHGNR_JEST AS CHGNR_JEST,
        join_4.OBJNR_JCDS AS OBJNR_JCDS,
        join_4.STAT_JCDS AS STAT_JCDS,
        join_4.CHGNR_JCDS AS CHGNR_JCDS,
        join_4.USNAM_JCDS AS USNAM_JCDS,
        join_4.UDATE_JCDS AS UDATE_JCDS,
        join_4.UTIME_JCDS AS UTIME_JCDS,
        join_4.TCODE_JCDS AS TCODE_JCDS,
        join_4.CDTCODE_JCDS AS CDTCODE_JCDS,
        join_4.INACT_JCDS AS INACT_JCDS,
        join_4.CHIND_JCDS AS CHIND_JCDS,
        join_4.WAERS_EQUI AS WAERS_EQUI,
        join_4.TXT04_TJ30T AS TXT04_TJ30T,
        join_4.TXT30_TJ30T AS TXT30_TJ30T,
        join_4.LTEXT_TJ30T AS LTEXT_TJ30T,
        join_4.TXT04_TJ02T AS TXT04_TJ02T,
        join_4.TXT30_TJ02T AS TXT30_TJ02T,
        join_4.ANSWT_EQUI AS ANSWT_EQUI,
        join_4.DURATION AS DURATION,
        "TXT30_TJ02T"+"TXT30_TJ30T" AS DESCRIPTION
    FROM join_4
  )

SELECT EQUNR_EQUI, OBJNR_EQUI, STAT_JEST, INACT_JEST, CHGNR_JEST, OBJNR_JCDS, STAT_JCDS, CHGNR_JCDS, USNAM_JCDS, UDATE_JCDS, UTIME_JCDS, TCODE_JCDS, CDTCODE_JCDS, INACT_JCDS, CHIND_JCDS, ANSWT_EQUI, WAERS_EQUI, DURATION, TXT04_TJ30T, TXT30_TJ30T, LTEXT_TJ30T, TXT04_TJ02T, TXT30_TJ02T, DESCRIPTION FROM projection